%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Y:\projects\intelligent-data-analysis\Homework 3\StudentData2.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/03 17:29:54

%% Import the data
[~, ~, raw] = xlsread('.\StudentData2.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
d1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;