%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Y:\projects\intelligent-data-analysis\Homework 1\DataHW1.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/30 14:25:21

%% Import the data
[~, ~, raw] = xlsread('DataHW1.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
DataHW1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;