%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Y:\projects\intelligent-data-analysis\Homework 2\data_banknote_authentication.xlsx
%    Worksheet: data_banknote_authentication
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/09 17:50:26

%% Import the data
d1 = xlsread('.\data_banknote_authentication.xlsx','data_banknote_authentication');

%% Create output variable
d1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;